### ISSUE TITLE
Extend functionality of panels

### ISSUE THREAD

**Issue by simurai** [atom/atom-ui#13]
Currently Atom provides [Panels](https://atom.io/docs/api/v1.9.9/Panel). But they are only "containers". Would be nice if they would provide more functionality, like:
- resizable
- dockable (pinned)
- dismissible (esc)
- have tabs
- maybe a header

Ref: https://github.com/atom/atom/issues/13502

**Comment by simurai** [comment]
Here some screenshots from @joefitzgerald that show what direction it could go:

![screen_shot_2016-08-22_at_2 49 17_pm_720](https://cloud.githubusercontent.com/assets/378023/17872161/bfb7df54-68f9-11e6-97aa-54cb64b467cb.png)
![slack-imgs com](https://cloud.githubusercontent.com/assets/378023/17872162/bfb8fb8c-68f9-11e6-9c10-f729626e6cfd.gif)
![slack-imgs com](https://cloud.githubusercontent.com/assets/378023/17872163/bfbad83a-68f9-11e6-84ad-9a32d705bafb.png)
![slack-imgs com](https://cloud.githubusercontent.com/assets/378023/17872164/bfbb0986-68f9-11e6-89d1-d2bf7a9846ea.jpeg)

**Comment by joefitzgerald** [comment]
These ideas are also very conceptually similar to the chromium inspector, if you ignore all the functionality inside it.

## Docked To The Bottom

![screen shot 2016-08-22 at 3 53 54 pm](https://cloud.githubusercontent.com/assets/744740/17873089/bcc97c68-6880-11e6-8dbf-3f963463ba38.png)

## Docked To The Side

![screen shot 2016-08-22 at 3 53 33 pm](https://cloud.githubusercontent.com/assets/744740/17873091/c22b67a2-6880-11e6-8309-b14f288bd723.png)

**Comment by simurai** [comment]
Some sort of "accordion" component would be useful too. Similar to the tree-view but just one level.

![screen shot 2016-08-23 at 1 21 50 pm](https://cloud.githubusercontent.com/assets/378023/17880364/df8ba456-6934-11e6-8fd2-fd4980ec605a.png)

Maybe could be done with a bunch of `<details>` element: https://developer.mozilla.org/en/docs/Web/HTML/Element/details

**Comment by joefitzgerald** [comment]
Nuclide actually uses either the chromium debugger ux, or creates an almost perfect replica:

![](https://nuclide.io/static/images/docs/feature-debugger-basics-debugger-example.png)

**Comment by simurai** [comment]
Happened in https://github.com/atom/atom/pull/13977
