### ISSUE TITLE
FileError: 'ui-variables.less' wasn't found.

### ISSUE THREAD

**Issue by ghost** [atom/atom-ui#6]
Many .less files in [atom-ui](https://github.com/atom/atom-ui) try to `@import "ui-variables";` or `@import "octicon-mixins";` when it doesn't exist.

**Reproduction Steps:**
1. `git clone https://github.com/atom/atom-ui`
2. `cd atom-ui`
3. `npm install less`
4. `lessc atom-ui.less`

**Expected behavior:**

`atom-ui.less` compiles into `atom-ui.css` without any error.

**Observed behavior:**

``` bash
FileError: 'ui-variables.less' wasn't found. Tried - /home/user/atom-ui/styles/ui-variables.less,/home/user/atom-ui/ui-variables.less,ui-variables.less in /home/user/atom-ui/styles/tooltip.less on line 1, column 1:
1 @import "ui-variables";
2 
```

A [search](https://github.com/atom/atom-ui/search?utf8=%E2%9C%93&q=ui-variables) for `ui-variables.less` returns nothing yet so far, is this intentional?

**Comment by simurai** [comment]
@citrusui `@import "ui-variables";` loads the variables that Atom themes provide.. like [this one](https://github.com/atom/one-dark-ui/blob/master/styles/ui-variables.less). But that only works inside of the Atom editor.

You might could clone an Atom theme and then change the path to something like: `@import "../some-atom-theme/styles/ui-variables";`. But this package isn't really meant to be used outside of Atom. I should add a note about it in the README.

**Comment by ghost** [comment]
OH. So I guess I should try compiling one-dark-ui then.

**Comment by simurai** [comment]
Actually.. `one-dark-ui` also imports:

```
@import "ui-variables-custom";
@import "syntax-variables";
```

 from the "[Syntax theme](https://github.com/atom/one-dark-syntax/blob/master/styles/syntax-variables.less)".

Which then also imports:

```
@import "colors";
```

It's long chain of imports. :see_no_evil:
